### ISSUE TITLE
Austreten von Rauch

### ISSUE THREAD

**Issue by CoretechR** [phi-el/Sticker-Collection#2]
Hi, I just saw this awesome sticker and had to recreate it.
Do you want to add it yourself or should I create a pull request?
![Mögliches Austreten von Rauch](https://github.com/phi-el/Sticker-Collection/assets/13223470/61cd14c0-ac44-4c58-ad19-10aff1ffaca3)

**Comment by phi-el** [comment]
Thanks for contributing @CoretechR ! :)

**Comment by CoretechR** [comment]
Gerne!
